version: '3.8'

services:
  dev:
    build:
      context: .
    privileged: true
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        ./scripts/entrypoint.sh
        /bin/bash
    tty: true
    stdin_open: true
    user: dev
    volumes:
      - ..:/workspace
      - ~/.ssh:/home/dev/.ssh
    networks:
      - ros2-network

  ci:
    build:
      context: .
    privileged: true
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        ./scripts/ci.sh
    tty: true
    stdin_open: true
    volumes:
      - ..:/workspace

networks:
  ros2-network:
    driver: bridge