name: Docker Build and Push to ECR Private with remote cache

on:
  push:
    branches: [ "release" ]

env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: robotsw/test

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout stack repository
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::557571393534:role/github-actions
        aws-region: ap-northeast-2

    - name: Login to Amazon ECR
      id: login_ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Set metadata for container image
      uses: docker/metadata-action@v2

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./docker/Dockerfile
        push: true
        tags: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPOSITORY }}:latest
        cache-from: type=registry,ref=557571393534.dkr.ecr.ap-northeast-2.amazonaws.com/robotsw/test:cache
        cache-to: type=registry,ref=557571393534.dkr.ecr.ap-northeast-2.amazonaws.com/robotsw/test:cache,mode=max
